---
title: "2024-02-12 积极和承担"
date: 2024-02-12
---

## Journal

### 关于主动积极责任承担

已经颇有种余音绕梁的感觉了，既然触动这么深，那就要记得久一点才是。

1. 主动
    - 自发地采取行动或决策，而不是被动等待事情发生或被别人告知需要做什么
    - 在工作或者社交场合看到机会或者潜在问题的时候，自发地行动以抓住机会或者预防解决问题
2. 积极
    - 指一个人的态度和对待生活事件的方式。积极的态度意味着乐观、寻找解决方案的心态，以及面对困难时保持正面的情绪。
    - 在生活或者工作上保持正向能量，鼓励他人、通过积极的反馈提供帮助
3. 责任
    - 涉及到对自己的行为、决策以及它们对他人的影响承担心理和社会义务。
    - 在各种事务中中完成自己的角色，按时按量完成任务，在问题出现时寻找解决方案而不是推卸
4. 承担
    - 意味着接受并且完成任务或者责任，不仅仅是接受分配，也包括在发现需要帮助的场景时，自愿提供帮助
    - 在面对责任或者挑战时，愿意承担责任并且寻求解决方案，用于面对后果并努力纠正

咨询了一下ChatGPT，再结合我自己的想法，尝试做一下结合：

要从相对被动、不积极的状态转向主动、积极、负责人、愿意承担的态度方向，无论是行动上还是思想上，
都需要培养一种特定的心态。这种转向意味着需要改变自己和自己、他人以及社会的关系的看法。

#### 想法层面

用思想这个词感觉尬得很。

1. 成长心态
    - 相信自己的能力和条件，并且相信努力、学习和坚持可以带来进步，将挑战和失败看作成长和学习的机会
    - 这一点似乎我在某些方面做得很好，毕竟我自己都取名“学习者”了；但是在其他一些领域，比如所谓社交，
    公开演讲等等一些不太擅长的方向，我似乎给自己设限很多，应该给自己松松绑
2. 责任心态
    - 承认个人对自己和周遭的生活负有责任，自己的行动和选择会产生影响
    - emm，这一点之前确实可能有意识，但不会特别主动地去想
3. 解决问题
    - 面对难题时，不问“为什么是我”，而是“我如何克服”
    - 这一点上，我觉得首先我确实不会为“为什么是我”这个问题，我应该非常少会抱怨自己或是自己的条件，
    同时我也觉得，我的努力程度不足以让我有资格抱怨这些，不过距离“如何克服”这个状态确实还是有一定距离
4. 感恩心态
    - 专注于生活中积极的方面，感激你所拥有的。这种态度有助于保持积极的情绪，即使在面对挑战时也能保持乐观
    - 这点我做的很挺好的，虽然过去没有很积极，但是一直还是挺感恩周遭的，这点继续保持就好
5. 开放心态
    - 对新体验、新观点保持开放态度，愿意学习和改变
    - 之前的状态，愿意学习但似乎不够开放？我理解这个可能和好奇心有一些关联吧，现在确实在改善中

#### 事件层面

1. 设定具体目标
2. 做前审视
    - 在做事和说话前，如果有能够反应的时间，尽量用这些目标来提前审视自己的答案，及时进行修正
    - 如果事前不能充分思考，事后尽可能也要尽快修正
    - 可能会有些累，但这样应该是很有必要的
2. 自我反思
    - 定期反思自己的行为和心态
3. 寻求反馈
4. 持续学习

### 关于公益捐赠

过年的前两天，看了B站上关于胡雷的视频，以及近期一些新闻，深感自己过的还是相当幸福了，
一直以来，我应该都不算是一个热衷于公益的人，小时候班级捐款似乎还有些积极，大学以后就基本不再关注这方面了。

因为2023年开始认真研究宏观的缘故，才注意到了社会上还有这么多生活不如意的人事物，打算从2024年开始，
每年捐出自己年收入的0.5%～1.0%左右给到陌生周遭，暂时还不舍得捐助太多，个人的修行还比较初级，
不过希望能够伴随着自己资产的上升，逐渐增加对周围的帮助，做一点点让自己更开心，也让他人能开心些的事情。
促使我做这些的也没什么特殊的，我也并没有领悟到更深的感受，就是感觉应该做一点了。

暂定的用途是这两类：

- 一半以上的部分应该会考虑捐助给韩红基金会
- 一小部分应该会用来捐助小区的流浪猫的一些费用
- 预算不多，这两个渠道应该很够了，不过如果生活周围有发现其他靠谱的，应该也会参与

### 关于容易被感动这件事

近段时间以来，感觉自己特别容易被感动或者触动，看电影容易掉眼泪、听抒情歌容易掉眼泪、听军歌容易红眼眶、
看积极奉献爱心的视频容易掉眼泪，看到喜欢的女生掉眼泪自己半夜也难受的掉眼泪... 很奇怪，突然之间，
生活中让我掉眼泪的事情和频率高了非常多，我猜想可能是因为内心放开了一些？或许，虽然我平时似乎也感觉不太到自己很封闭，
不过应该是一种好的改变吧，该哭哭该笑笑，人前也许还有必要忍一忍，独处之时似乎没什么不能掉眼泪的原因，
能因为简单的事情哭出来，大概也是我希望自己不变的一部分吧。

## Cooking

{{< include 2024-02-12-cooking.qmd >}}
