---
title: "2024-02-10 龙年第一天"
date: 2024-02-10
---

### Journal

龙年，大年初一。不知道是什么原因，或许是岁数又长了？感觉这个年似乎过得越来越冷静了，今年我观看春晚的时间创造了历史记录，
几乎没正眼瞧过一眼，据说老家的鞭炮燃放数量破了记录，不过感觉上海家里周边的鞭炮声音都是没有印象里的多，持续时间和热烈程度都不高，
或许财神那天会更多么？还是要提醒自己谨记投资不能靠身边的感觉，需要宏观数据是能够印证才能作为依据。

今天终于把这个想了不知道多久一直拖延的blog给弄起来了，虽然配置起来挺费劲，不过真弄完了感觉还有那么一丢丢成就感。

促使我开始记录的最大原因，应该就是我最近的一次正在进行中的相亲经历，还真就挺特别的，很多感觉混混沌沌的，出现了太多同时出现的相反的讯号，
对我这种EQ渣来说，还真是想不清楚，无论如何，反正我挺喜欢这个女生的，不过这些都不是重点，今天，我只想很功利地盘点一下我所收获的：

no.1，首当其冲应该就是对于运动建立起了初步的兴趣吧，这想想真的很神奇，真的是遇到特别的人充当了催化剂的作用，所以就能点燃自己对运动的兴趣吗？
我在想，会不会有另一种可能，是因为我需要和这个女生有交流，我想要在自己平淡无奇的生活中找出一些亮点来分享，
这个角度诱发了我在运动过程中对于自身感受和周围环境变化的细致观察，一方面是这样的努力让我从运动中那种身体酸痛劳累的感觉中抽离出来了一些，
让我自己多发现了一些运动时身边的小乐趣，两相结合让运动过程不像原先那样难以坚持；另一方面可能是之前断断续续运动成果的积累，
在我近期的比较规律、自律的训练中获得了一定程度的兑现，让我在这段期间享受到了许多运动的积极成果。
可能有这方面的因素，不过似乎还是脱离不了这个女生的作用，应该确实是她的出现的功劳。

no.2，对于世界的好奇心，这点其实和第一点的想法比较像，就不多赘述了，这件事情是一件特别好的事情么，也许，也许不是，
不过我想作为一种改变来说，在没有变坏的情况下，总归是不错的。

no.3，主动积极责任担当，这现在是我脑海中经常盘旋的八个大字，不得不说，特别的人说似乎确实有特别的作用，以往这些听不进去的词似乎都很顺耳了，
无论是想法上、还是行动上，我都开始积极地从这些词的角度来审视自己的观点，开始修正可能与之偏离的行为，老实讲，能改多少，能不能改相当的比例，
我自己也不太确定，虽然从积极上来说不应该这么想，不过思想的改变总是相对困难的，还是实事求是一些。

no.4，对于未来的规划的战略清晰，在此之前，我对于自己的plan一直是一种战略模糊的状态，"I don't even have a pla."，这句真是不可谓不形象，
被这个女生和房产问题的突然到来，我感觉自己似乎破除了眼前的一道纱，也许这会蹦出来另一个问题，那之前一段恋爱中也面临了买房问题，
为什么当时没有改变呢？我好像并没有特别想通，不过我猜测，可能和我自己当时的月光处境有关系，当自己没有一定的现实条件或是做出一定程度的努力时，
遇到类似的无能为力的事情可能只能踩西瓜皮吧，而这次遇到这件事的时候，我已经从当时的月光状态到了长时间持续攒钱的情况，甚至投资收益暂时还不错，
这都让我有了认真考虑未来的基础，虽然距离女生的要求似乎还是挺远的，但对于我自己来说，也算是迈出了一大步吧。

目前想到的主要是这四点，写的很浅，只是简单带过，未来有契机的时候我希望自己能够一项一项详细描述，另外，关于亲密关系的想法、关于亲子关系的想法也有一点程度的改变，
这些应该都值得去详细写出来作为未来的参照。其实，这段过程中本身的一些经历和特点也值得让我多去想一想，不过这或许在我把买房问题和父母沟通到有个初步结果以后再说可能比较合适，
毕竟起码关系的短期走向可能也会比较明确了。

anyway，今天又是没和这个女生说话的一天，真的挺神奇～～

最后，今天终于正式开始了账本的清欠工作，道阻且长，但可喜可贺。构思许久的投资面板思路还是有些迷茫，不过感觉也是时候先做一版出来看看再继续想了。
做了道简易家常菜，nice；也维持了最基本的训练，一些很久没做的程度也有了不错的提升，happy。

另外对于这个blog，也许之后应该把日记和训练记录、做菜记录放在一起，或许会更合适？现在这种拆分的方式似乎让浏览体验差了一些些，可以再想想这个问题。

END.

### Workout

{{< include 2024-02-10-workout.qmd >}}

### Cooking

{{< include 2024-02-10-cooking.qmd >}}
