project:
  type: website
  render:
    - "*.qmd"
    - "!*-cooking.qmd"
    - "!*-workout.qmd"

website:
  title: "SID's"
  navbar:
    # background: primary
    search: true
    right:
      - text: Journals
        href: journals/index.qmd
      - text: Workouts
        href: workouts/index.qmd
      - text: Cooking
        href: cooking/index.qmd
  sidebar:
    - title: "Journals"
      contents: journals

    - title: "Workouts"
      # style: "docked"
      contents: workouts

    - title: "Cooking"
      contents: cooking

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    grid:
      body-width: 1000px

