project:
  type: website
  preview:
    port: 8001
  render:
    - "*.qmd"
    - "!journals/**/*-cooking.qmd"
    - "!*-workout.qmd"

website:
  title: "SID's"
  site-url: https://me.sidkang.com
  description: "A simple pseronal blog"
  favicon: images/profile.jpeg
  navbar:
    # background: primary
    search: true
    right:
      - text: Home
        href: index.qmd
      - text: Notes
        href: notes/index.qmd
      - text: Journals
        href: journals/index.qmd
      - text: Workouts
        href: workouts/index.qmd
      - text: Cooking
        href: cooking/index.qmd
      - text: About
        menu:
          - text: My Gear List
            href: about/gears.qmd
          - text: Markdown Cheatsheet
            href: about/markdown-cheatsheet.qmd

  sidebar:
    - title: "Notes"
      collapse-level: 3
      contents:
        - auto: notes

    - title: "Journals"
      collapse-level: 2
      contents:
        - section: "Journals"
          href: journals/index.qmd
          contents:
            - section: "2024"
              href: journals/2024/index.qmd
              contents:
                - journals/2024/weekly.qmd
                - section: "February"
                  contents:
                    - auto: journals/2024/02/*

    - title: "Workouts"
      # style: "docked"
      collapse-level: 3
      contents: workouts

    - title: "Cooking"
      collapse-level: 3
      contents: cooking

  page-footer:
    border: false
    left: "This page is built with ❤️  and [Quarto](https://quarto.org/)."
    right:
      - icon: twitter
        href: https://twitter.com/sidskang
      - icon: telegram
        href: https://t.me/sidkang

format:
  html:
    theme: 
      # - cosmo
      # - flatly
      - journal
      # - pulse
      # - materia
      # - litera
      - custom.scss
    css: styles.css
    toc: true
    toc-location: right
    html-math-method: katex
    smooth-scroll: true
    grid:
      body-width: 1000px

