---
toc: true
---

# 均衡宏观经济学方法论

对应书本第五、六章节

宏观经济学研究市场问题

1. supply -- enginering problem / natural science
2. demand -- effective question

Methodology on Natural Science


## 消费函数与持久收入假说

### 消费函数与乘数效应

根据支出法GDP的统计方式，社会总需求可以表达为

$$
Z=C+I+G+NX
$$ (gdp_equation)

引入凯恩斯在《就业、利息和货币通论》中所提出的————社会中的总消费是总产出的线性函数，凯恩斯称为**消费函数(consumption function)**

$$
C=c_0+c_1Y
$$ (consumption_function)

等式(consumption_function)中，$c_0$是消费者的最低消费（收入为0时的消费)，$c_0>0$，$c_1$是消费的边际倾向,$0<c_1<1$

所以，将{eq}`consumption_function`引入{eq}`gdp_equation`后，

\begin{align*}
Z=c_0+c_1Y+I+G+{NX}
\end{align*}

同时，因为$Z=Y$，所以

\begin{align*}
Y=c_0+c_1Y+I+G+{NX}
\end{align*}

将上述等式变换后，可得到著名的 `IS曲线`，其中，$c_0+I+G+NX$叫做`自发性支出(autonomous spending)`，指居民、企业、政府能自主选择的支出

$$
Y=\frac{1}{1-c_1}(c_0+I+G+NX)
$$ {#eq-is_curve_equation}

::: {#cor-multiplier-effect}
## Multiplier Effect

Given $0<c_1<1$, so $1/(1-c_1)>1$

根据 @eq-is_curve_equation 可得

1. 自发性支出中任意一项变每变动1单位，则最终经济产出变化一定超过1单位；
2. 对付政府而言，每增加1单位的支出，通过乘数效应可得到超过1单位的经济产出，故政府可以通过调节政府支出已达到扩张或收缩经济总需求
:::

### 持久收入假说



## 芬利普斯曲线的消失(Phillips Curve)

菲利普斯曲线由威廉·菲利普斯在1958年研究英国经济数据的时候提出，菲利普斯曲线指失业率和通货膨胀率之间存在一定负相关的关系，随后，在美国等国家的经济数据中也发现了这一现象。
在随后的70年代石油危机爆发后，各国失业率快速上升，各国政府有意识的推高通胀率以降低失业率，但在实践中，大家发现菲利普斯曲线的规律消失了，高通胀+未能降低的失业率带来了新的困境————`滞涨(stagflation)`

::: {.callout-warning}
补充菲利普斯曲线作图
:::

::: {.callout-tip}
## Tip With Caption

This is an example of a callout with a caption.
:::

### 自然科学的研究方法

## 理性预期革命

```{admonition}
卢卡斯批判(Lucas Critique)
1975年，罗伯特·卢卡斯发表《经济计量政策评估：一项评论》
```

宏观分析与微观现象的关系?

::: {.callout-tip collapse="true"}
#### 为什么消费函数被批判不恰当，那为什么仍然可以使用供给函数？

需求函数因为是在刻画人的消费行为，但人的想法受到宏观变量的改变也会改变，想法改变也意味着行为的改变；而供给函数实际描述的是`产出潜力`，是一种自然科学类的描述方式，以什么样的技术水平，投入多少的人力和资本等客观要素可以达到什么样的产量
:::

## 均衡经济学方法论

经济学在研究时所面临的难题，人的思想不可预测，人的行为也无法预测，未来会成为新的现实基础，又会对人的思想产生影响

```{mermaid}
flowchart LR
Reality --> a1[Rational Human Minds] --> a2[Rational Human Behaviors] --> Future
```

理性人假设

what 使用理性人假设非理性带来的可能行为，限制可能的行为集

why 对于理性的最优反应是理性，对非理性的最优反应不是非理性;理性的实体将在竞争中占领优势地位，淘汰相对非理性的实体，从长期来看，竞争实体趋向于理性

cost 理性人假设所导致的代价
1. 容易忽视或看不到非理性行为和相应的后果
2. 在分析过程中抽离了人性

## 单期宏观经济一般均衡模型

在经济学中，“看不见的手”用来描述一种`均衡`状态，放在宏观经济中，则被称为`一般均衡(general equilibrium)`



## 一般均衡与福利

## 中国经济的数量分析

## 课后练习

::: {.callout-note appearance="simple"}
“卢卡斯批判”说的是，建立在人的行为之上的统计关系是不稳定的，会因为人行为方式的改变而改变（比如菲利普斯曲线的消失）。因此，我们要从人的偏好、人的理性出发来进行经济分析。

但如果人的偏好会随着时间的变化而变化呢？比如，人在经济繁莱时更偏好闲暇，在经济衰退时更偏好消费。基于这种可变化的偏好而形成的统计关系是稳定的吗？还会继续受到卢卡斯的批评吗？为什么？
:::

::: {.callout-tip collapse="true" }
## 答案

卢卡斯批评指出的是**用观察到的历史数据之间的数量关系来评价经济政策调整的效果是无效的**，是指讲人的经济行为与宏观经济研究两者割裂开的研究方式不可行。宏观经济模型是从微观个体的理性出发，以各个相关主体的最优化问题作为宏观建模的基础。在思考宏观政策时，也应充分预估到各主体对于宏观政策的最优反应。

在考虑到宏观政策对于个体偏好选择的影响的时候，经济环境及政策对于人的偏好选择的影响也是有一定规律，可以分析出一定的理性行为，那么在这种考量基础上进行的宏观建模工作，也是拥有微观基础的理论，是卢卡斯批判所赞同的研究范式。
:::


::: {.callout-note appearance="simple"}

有人批评经济学的“理性 人”假设要求太高，真实世界里的人不可能都是理性的。他们因此认为建立在理性人假设之上的经济分析没有意义。你该怎样反驳他们的观点？
:::

::: {.callout-tip collapse="true"}
#### 答案

在本讲`5.3`节的模型中，现在假设两个厂商生产产品的单位成本均为1,两个厂商共同面对的需求曲线方程为

$$
p_t=a_t-0.5(q_{1t}+q_{2t})
$$

1. 如果厂商一用自然科学的研究方法来分析这个问题，将自己的产量固定在8，会观察到厂商二的产量与需求冲击 $a_t$ 之间有何种关系？基于这样的对厂商二的行为的认知，厂商一在需求冲击 $a_t=20$ 的时候会给自己选择多大的产量？获得的利润是多少？
2. 如果厂商一用正确的经济学分析方法来研究这个问题，它应该在需求冲击 $a_t=20$ 的时候选择什么样的产量？获得多少利润？
:::